infra:
    log_dir: /data1/dri/hlss/hlss/exps/Exp020 # where all the experiments are
    exp_name: a # create a subdirectory for each set of experiments
    comment: patient_disc_dev # can use this to customize for each experiment
    seed: 1000
data:
    db_root: /data1/dri/hlss/hlss/datasets/opensrh
    data_classes : ['Cellularity', 'Nuclear Pleomorphism', 'Vascularity', 'Tissue Architecture', 'Necrosis', 'Cell Infiltration', 'Inflammatory Response', 'Molecular Markers', 'Lipid Content', 'Protein Density', 'Nucleic Acid Presence', 'Cellular Morphology', 'Chemical Composition', 'Microcalcifications', 'Cytoplasmic Inclusions', 'Stromal Components', 'Mitotic Figures', 'Myelin Content', 'Cell Density', 'Nuclear Size Variation', 'Cell Clustering', 'Cell Dispersal', 'Cell Border Definition', 'Mitotic Activity', 'Cell Shape Irregularity', 'Nuclear-Cytoplasmic Ratio', 'Pleomorphic Cell Types', 'Cellular Pleomorphism', 'Nuclear Shape Irregularity', 'Chromatin Pattern', 'Nuclear Membrane Distortion', 'Nuclear Grooves', 'Hyperchromasia', 'Heterogeneity of Nuclei', 'Abnormal Nuclear Structure', 'Blood Vessel Size', 'Blood Vessel Density', 'Blood Vessel Morphology', 'Vascular Patterning', 'Blood Vessel Integrity', 'Presence of Angiogenesis', 'Vascular Leakage', 'Pericyte Coverage', 'Vascular Tortuosity', 'Hemorrhage', 'Geographic Necrosis', 'Pseudo-Palisading Necrosis', 'Central Necrosis', 'Necrotic Patterns', 'Apoptotic Bodies', 'Lymphocytic Infiltration', 'Macrophage Infiltration', 'Presence of Neutrophils', 'Immune Cell Aggregates', 'Inflammatory Patterns', 'Presence of Plasma Cells', 'Eosinophil Infiltration', 'Granulocyte Infiltration', 'Inflammatory Cytokine Expression', 'Immune Cell Localization', 'Genetic Mutations', 'Expression of Specific Proteins', 'Altered Protein Phosphorylation', 'Fusion Genes', 'Altered Apoptosis Regulators', 'Epigenetic Changes', 'Aberrant Protein Phosphorylation', 'Presence of Fusion Genes', 'Altered Expression of Apoptosis Regulators', 'Presence of Specific Molecular Markers', 'Lipid Droplet Presence', 'Lipid Droplet Size Variation', 'Lipid Droplet Distribution', 'Lipid Droplet Morphology', 'Lipid-Rich Regions', 'Lipid Vacuoles', 'Lipid Microdomains', 'Lipid Content Grading', 'Lipid Inclusions in Cells', 'Lipid Droplet Aggregates', 'Protein Accumulation in Nuclei', 'Protein-Rich Vesicles', 'Perinuclear Protein Patterns', 'Protease Digestion Resistance', 'Protein Microdomains', 'Protein Distribution Gradients', 'Protein Cluster Formation', 'Protein Aggregates', 'Protein Localization Patterns', 'Protein Concentration Variability', 'DNA Localization', 'RNA Localization', 'Nucleic Acid Distribution', 'DNA-RNA Co-Localization', 'Detection of Specific Gene Sequences', 'Nucleic Acid Aggregates', 'Nucleic Acid-rich Regions', 'Nucleic Acid Dot Structures', 'Nucleic Acid Inclusions', 'Nucleic Acid Staining Patterns', 'Chemical Component Diversity', 'Specific Molecule Detection', 'Metabolite Localization', 'Chemical Component Gradients', 'Chemical Component Aggregations', 'Detection of Metabolic Byproducts', 'Differences in Metabolite Concentrations', 'Chemical Component Variation Across Regions', 'Metabolite-Rich Regions', 'Metabolic Pathway Indicators', 'Fibrous Tissue Density', 'Collagen Fiber Presence', 'Stromal Aggregations', 'Stromal Fiber Thickness', 'Stromal Fiber Morphology', 'Stromal Localization Patterns', 'Stromal Tissue Grading', 'Stromal Component Aggregates', 'Stromal Fiber Distributions', 'Stromal Component Composition', 'Mitotic Figure Frequency', 'Mitotic Figure Morphology', 'Mitotic Figure Localization', 'Mitotic Figure Size', 'Myelin Presence', 'Myelin Fiber Density', 'Myelin Fiber Size', 'Myelin Staining Intensity']
    patch : {
    "Cellularity", "Nuclear Pleomorphism", "Lipid Content", "Protein Density", "Nucleic Acid Presence",
    "Cellular Morphology", "Microcalcifications", "Cytoplasmic Inclusions", "Mitotic Figures", "Myelin Presence",
    "Cell Density", "Nuclear Size Variation", "Cell Clustering", "Cell Dispersal", "Cell Border Definition",
    "Mitotic Activity", "Cell Shape Irregularity", "Nuclear-Cytoplasmic Ratio", "Pleomorphic Cell Types",
    "Cellular Pleomorphism", "Nuclear Shape Irregularity", "Chromatin Pattern", "Nuclear Membrane Distortion",
    "Nuclear Grooves", "Hyperchromasia", "Heterogeneity of Nuclei", "Abnormal Nuclear Structure",
    "Lipid Droplet Presence", "Lipid Droplet Size Variation", "Lipid Droplet Distribution", "Lipid Droplet Morphology",
    "Lipid-Rich Regions", "Lipid Vacuoles", "Lipid Microdomains", "Lipid Content Grading", "Lipid Inclusions in Cells",
    "Lipid Droplet Aggregates", "Protein Accumulation in Nuclei", "Perinuclear Protein Patterns", "Protease Digestion Resistance",
    "Protein Microdomains", "Protein Distribution Gradients", "Protein Cluster Formation", "Protein Aggregates",
    "Protein Localization Patterns", "Protein Concentration Variability", "DNA Localization", "RNA Localization",
    "Nucleic Acid Distribution", "DNA-RNA Co-Localization", "Detection of Specific Gene Sequences", "Nucleic Acid Aggregates",
    "Nucleic Acid-rich Regions", "Nucleic Acid Dot Structures", "Nucleic Acid Inclusions", "Nucleic Acid Staining Patterns",
    "Chemical Component Diversity", "Specific Molecule Detection", "Metabolite Localization", "Chemical Component Gradients",
    "Chemical Component Aggregations", "Detection of Metabolic Byproducts", "Differences in Metabolite Concentrations",
    "Chemical Component Variation Across Regions", "Metabolite-Rich Regions", "Metabolic Pathway Indicators",
    "Fibrous Tissue Density", "Collagen Fiber Presence", "Stromal Aggregations", "Stromal Fiber Thickness",
    "Stromal Fiber Morphology", "Stromal Localization Patterns", "Stromal Tissue Grading", "Stromal Component Aggregates",
    "Stromal Fiber Distributions", "Stromal Component Composition", "Mitotic Figure Frequency", "Mitotic Figure Morphology",
    "Mitotic Figure Localization", "Mitotic Figure Size", "Myelin Fiber Density", "Myelin Fiber Size", "Myelin Staining Intensity",
    "Nuclear Pores Presence","Nuclear Folds","Cellular Orientation","Cell Membrane Integrity","Microvilli Presence",
    "Nuclear Hypersegmentation","Chromosomal Aberrations","Nuclear Body Formation","Cytoplasmic Vacuolization","Cellular Fracturing",
    "Nuclear Blebbing","Cellular Swelling","Mitochondrial Density","Peroxisome Distribution","Ribosomal Aggregates",
    "Endoplasmic Reticulum Morphology","Glycogen Granule Presence","Cytoskeleton Arrangement","Nuclear Spindle Formation",
    "Centrosome Abnormalities","Microtubule Disruptions","Cellular Bridges","Cellular Cannibalism","Nuclear Pseudoinclusions",
    "Chromosomal Bridges","Cellular Atypia","Nuclear Enlargement","Cytoplasmic Granulation","Nuclear Folding Patterns",
    "Centriole Duplication","Peroxisomal Aggregations","Ribosomal RNA Localization","Nuclear Chromocenters","Cellular Invaginations",
    "Nuclear Vacuolization","Golgi Apparatus Integrity","Cytoplasmic Blebbing","Endocytic Vesicle Presence","Lysosomal Accumulation",
    "Cellular Repulsion","Mitotic Slippage","DNA Damage Foci","Nuclear Malformations","Microtubule Bundles","Chromatin Granularity"
}

    slide : {
    "Vascularity", "Tissue Architecture", "Necrosis", "Cell Infiltration", "Inflammatory Response",
    "Molecular Markers", "Blood Vessel Size", "Blood Vessel Density", "Blood Vessel Morphology", "Vascular Patterning",
    "Blood Vessel Integrity", "Presence of Angiogenesis", "Vascular Leakage", "Pericyte Coverage", "Vascular Tortuosity",
    "Hemorrhage", "Geographic Necrosis", "Pseudo-Palisading Necrosis", "Central Necrosis", "Necrotic Patterns", "Apoptotic Bodies",
    "Lymphocytic Infiltration", "Macrophage Infiltration", "Presence of Neutrophils", "Immune Cell Aggregates",
    "Inflammatory Patterns", "Presence of Plasma Cells", "Eosinophil Infiltration", "Granulocyte Infiltration",
    "Inflammatory Cytokine Expression", "Immune Cell Localization", "Genetic Mutations", "Expression of Specific Proteins",
    "Altered Protein Phosphorylation", "Fusion Genes", "Altered Apoptosis Regulators", "Epigenetic Changes",
    "Aberrant Protein Phosphorylation", "Presence of Fusion Genes", "Altered Expression of Apoptosis Regulators",
    "Presence of Specific Molecular Markers", "Tumor Margin Definition","Stromal Infiltration",
  "Tumor Microenvironment Characteristics","Tumor Border Irregularity","Stromal Matrix Composition",
  "Extracellular Matrix Features","Cellular Density Gradients","Cellular Organization",
  "Tumor Stroma Heterogeneity","Stromal Tissue Remodeling","Tumor-Associated Fibroblast Density",
  "Stromal Inflammatory Infiltration","Tumor-Adjacent Tissue Interaction","Stromal Vascular Support",
  "Stromal Immune Cell Composition","Tumor-Stromal Interface Patterns","Tumor-Adjacent Tissue Morphology",
  "Peritumoral Edema","Tumor Margin Smoothness","Tumor Stroma Collagen Distribution",
  "Stromal Cellularity","Peritumoral Lymphatic Density","Tumor Microenvironment Angiogenesis",
  "Tumor-Stroma Metabolic Interactions","Tumor-Stroma Signaling Crosstalk","Peritumoral Nerve Infiltration",
  "Tumor Margin Vascularization","Stromal Lymphatic Network","Peritumoral Fibrosis",
  "Tumor Microenvironment pH Levels","Tumor Margin Elasticity","Stromal Glycosaminoglycans",
  "Peritumoral Cytokine Expression","Tumor-Stroma Neurotransmitter Signaling","Tumor Margin Hypoxia Levels",
  "Stromal Lipid Accumulation","Peritumoral Cellular Stress Response","Tumor Microenvironment Extracellular Vesicles",
  "Tumor-Stroma Mechanical Properties","Peritumoral Oxidative Stress","Tumor Margin Immune Suppression",
  "Stromal Fibroblast Activation","Peritumoral Angiocrine Signaling","Tumor-Stroma Growth Factor Interactions",
  "Tumor Microenvironment Metabolomic Profiles","Peritumoral Stiffness","Tumor Margin Immune Cell Exhaustion",
  "Stromal Chemokine Gradients","Peritumoral Immune Cell Exhaustion","Tumor-Stroma Autophagy Levels",
  "Tumor Microenvironment MicroRNA Profiles","Peritumoral Immune Suppressive Factors","Tumor-Stroma Epigenetic Modifications",
  "Peritumoral Immune Cell Polarization","Tumor-Stroma Extracellular Vesicle Cargo","Tumor Microenvironment Immune Cell Trafficking",
  "Peritumoral Tissue Necroptosis","Tumor-Stroma Endothelial Cell Activation",
  "Peritumoral Extracellular Matrix Stiffness","Tumor Margin Neovascularization",
  "Stromal Tissue Tension","Peritumoral Immune Cell Trafficking Patterns","Tumor-Stroma Lymphatic Drainage",
  "Tumor Margin Mast Cell Infiltration","Stromal Tissue Innervation","Peritumoral Growth Factor Signaling",
  "Tumor-Stroma Myeloid Cell Infiltration","Tumor Microenvironment Stromal Cell Proliferation","Peritumoral Tissue Oxygenation",
  "Tumor-Stroma Natural Killer Cell Activity","Tumor Margin Tissue Perfusion","Stromal Tissue Viscosity",
  "Peritumoral Immune Cell Metabolism","Tumor-Stroma T Cell Infiltration",
  "Tumor Margin Collagen Crosslinking","Stromal Matrix Elasticity","Peritumoral Immune Cell Senescence",
  "Tumor-Stroma Matrix Metalloproteinase Levels","Tumor Microenvironment Cytokine Gradients","Peritumoral Vascular Endothelial Growth Factor",
  "Tumor-Stroma Chemokine Receptor Expression","Tumor Margin Immune Checkpoint Expression","Stromal Tissue Angiostatic Factors",
  "Peritumoral Tissue pH Levels","Tumor-Stroma Cell Adhesion Molecules","Tumor Microenvironment Immune Cell Exhaustion",
  "Peritumoral Tissue Glycoprotein Expression"
}

    patient : {
    "Chemical Composition", "Metabolic Pathway Indicators","Tumor Heterogeneity",
    "Growth Patterns","Satellite Lesions", "Tumor Borders","Vascular Network",
    "Peritumoral Characteristics","Microenvironment Morphology","Infiltrative Margins",
    "Tumor Angiogenesis","Necrosis Patterns","Stromal-Tumor Interaction","Vascular Supply",
    "Cellular Density","Margin Integrity","Immune Response","Vasculature Integrity",
    "Global Cellularity","Microenvironmental Heterogeneity","Inflammatory Patterns","Margin Perfusion",
    "Microarchitecture","Stromal-Tumor Crosstalk","Extracellular Matrix","Vascular Permeability",
    "Microenvironmental Vascularity","Global Proliferation","Margin Collagen Distribution","Immune Infiltration",
    "Immune Suppression","Apoptosis Levels","Lipid Content","Metabolic Crosstalk",
    "Protein Expression","Genetic Features","Molecular Signatures","Epigenetic Changes",
    "Cellular Morphology","Stromal Composition","Lipid Distribution","Nuclear Characteristics",
    "Stromal-Tumor Fusion Genes","Margin Tissue Differentiation","Nuclear-Cytoplasmic Ratio",
    "Chemical Diversity","Stromal Fiber Morphology","Stromal Aggregations",
    "Stromal Fiber Density","Cellular Heterogeneity","Stromal Matrix Integrity","Stromal Matrix Composition",
    "Stromal Matrix Remodeling","Stromal-Tumor Protein-Protein Interactions","Stromal-Tumor Tumor Margin Vascularization",
    "Stromal-Tumor Matrix Metalloproteinase Levels","Stromal-Tumor T Cell Infiltration",
    "Stromal-Tumor Natural Killer Cell Activity", "Stromal-Tumor Immune Cell Trafficking Patterns",
    "Stromal-Tumor Immune Cell Senescence",
    "Stromal-Tumor Growth Factor Signaling",
    "Stromal-Tumor Chemokine Receptor Expression",
    "Stromal-Tumor Extracellular Vesicle Cargo",
    "Tumor Margin Immune Checkpoint Expression",
    "Stromal-Tumor Signaling Crosstalk",
    "Stromal-Tumor Immune Exhaustion",
    "Stromal-Tumor Angiocrine Signaling",
    "Stromal-Tumor Extracellular Matrix Features",
    "Stromal-Tumor Immune Suppressive Factors",
    "Stromal-Tumor Extracellular Matrix Stiffness",
    "Stromal-Tumor Extracellular Matrix Remodeling",
    "Peritumoral Lymphatic Density",
    "Stromal-Tumor MicroRNA Profiles",
    "Stromal-Tumor Epigenetic Modifications",
    "Stromal-Tumor Immune Cell Trafficking",
    "Stromal-Tumor Tissue Necroptosis",
    "Stromal-Tumor Endothelial Cell Activation",
    "Peritumoral Tissue Oxygenation",
    "Stromal-Tumor Tissue Nucleotide Metabolism",
    "Stromal-Tumor Tumor Margin Neovascularization",
    "Stromal-Tumor Tissue pH Levels",
    "Stromal-Tumor Cell Adhesion Molecules",
    "Stromal-Tumor Tissue Tension",
    "Peritumoral Immune Cell Trafficking Patterns",
    "Stromal-Tumor Lymphatic Drainage",
    "Tumor Margin Mast Cell Infiltration",
    "Stromal-Tumor Tissue Innervation",
    "Stromal-Tumor Peritumoral Growth Factor Signaling",
    "Stromal-Tumor Tumor-Stroma Myeloid Cell Infiltration",
    "Stromal-Tumor Tumor Microenvironment Stromal Cell Proliferation",
    "Peritumoral Tissue Oxygenation",
    "Stromal-Tumor Tumor-Stroma Natural Killer Cell Activity",
    "Tumor Margin Tissue Perfusion",
    "Stromal-Tumor Tissue Viscosity",
    "Immune Cell Metabolism",
    "Tumor-Stroma T Cell Infiltration",
    "Margin Collagen Crosslinking",
    "Stromal Matrix Elasticity",
    "Immune Cell Senescence",
    "Matrix Metalloproteinase Levels",
    "Cytokine Gradients",
    "Vascular Endothelial Growth Factor",
    "Chemokine Receptor Expression",
    "Immune Checkpoint Expression",
    "Tumor-Stroma Growth Factor Interactions",
    "Immune Cell Exhaustion",
    "MicroRNA Profiles",
    "Immune Suppressive Factors",
    "Epigenetic Modifications",
    "Immune Cell Polarization",
    "Extracellular Vesicle Cargo",
    "Tissue Necroptosis",
    "Endothelial Cell Activation",
    "Tissue Oxygenation",
    "Tissue Nucleotide Metabolism",
    "Tumor Margin Neovascularization",
    "Tissue pH Levels",
    "Cell Adhesion Molecules",
    "Tissue Tension",
    "Immune Cell Trafficking Patterns",
    "Lymphatic Drainage",
    "Tumor Margin Mast Cell Infiltration",
    "Tissue Innervation",
    "Peritumoral Growth Factor Signaling",
    "Tumor-Stroma Myeloid Cell Infiltration",
    "Tumor Microenvironment Stromal Cell Proliferation",
    "Peritumoral Tissue Oxygenation",
    "Tumor-Stroma Natural Killer Cell Activity", "Tumor Metastasis Risk",
    "Patient-Specific Molecular Profiles","Tumor Microenvironment Immune Response"
}
    train_augmentation:
        - which: random_horiz_flip
          params: {}
        - which: random_vert_flip
          params: {}
        - which: gaussian_noise
          params: {}
        - which: color_jitter
          params: {}
        - which: random_autocontrast
          params: {}
        - which: random_solarize
          params:
            threshold: 0.2
        - which: random_sharpness
          params:
            sharpness_factor: 2
        - which: gaussian_blur
          params:
            kernel_size: 5
            sigma: 1
        - which: random_affine
          params:
            degrees: 10
            translate: [0.1, 0.3]
        - which: random_resized_crop
          params:
            size: 224
        - which: random_erasing
          params: {}
    valid_augmentation:
        - which: random_horiz_flip
          params: {}
        - which: random_vert_flip
          params: {}
        - which: gaussian_noise
          params: {}
        - which: color_jitter
          params: {}
        - which: random_autocontrast
          params: {}
        - which: random_solarize
          params:
            threshold: 0.2
        - which: random_sharpness
          params:
            sharpness_factor: 2
        - which: gaussian_blur
          params:
            kernel_size: 5
            sigma: 1
        - which: random_affine
          params:
            degrees: 10
            translate: [0.1, 0.3]
        - which: random_resized_crop
          params:
            size: 224
        - which: random_erasing
          params: {}
    rand_aug_prob: 0.3
    hidisc:
        num_slide_samples: 2
        num_patch_samples: 2
        num_transforms: 2
    balance_study_per_class: true
model:
    backbone: RN50
    mlp_hidden: []
    num_embedding_out: 128

    patch_templates : {'Cellularity': [
      'A histopathology slide showing high cellularity.', 
      'Histopathology image of highly cellular tissue.', 
      'Pathology tissue showing high cellularity.', 
      'Presence of highly cellular tissue o